# Generated by Django 5.1 on 2024-08-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='distrito',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='provincia',
            field=models.CharField(max_length=30),
        ),
    ]
