# Generated by Django 5.1 on 2024-08-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicioapp', '0002_alter_usuario_departamento_alter_usuario_distrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
